import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MAX_DEX_ID, generationForId } from '../src/utils/generations.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CACHE_DIR = join(__dirname, '.cache');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'data', 'pokedex.ts');

interface SpeciesName {
  name: string;
  language: { name: string };
}

interface SpeciesResponse {
  id: number;
  names: SpeciesName[];
}

interface PokedexEntry {
  id: number;
  nameEn: string;
  nameDe: string;
  generation: number;
}

mkdirSync(CACHE_DIR, { recursive: true });

async function fetchSpecies(id: number): Promise<SpeciesResponse> {
  const cachePath = join(CACHE_DIR, `${id}.json`);
  if (existsSync(cachePath)) {
    return JSON.parse(readFileSync(cachePath, 'utf-8'));
  }

  const maxAttempts = 3;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const res = await fetch(`https://pokeapi.co/api/v2/pokemon-species/${id}`);
      if (!res.ok) throw new Error(`HTTP ${res.status} for species ${id}`);
      const data = (await res.json()) as SpeciesResponse;
      writeFileSync(cachePath, JSON.stringify(data));
      return data;
    } catch (err) {
      if (attempt === maxAttempts) throw err;
      await new Promise((r) => setTimeout(r, 300 * 2 ** attempt));
    }
  }
  throw new Error('unreachable');
}

function extractName(species: SpeciesResponse, lang: string): string {
  const entry = species.names.find((n) => n.language.name === lang);
  if (!entry) {
    throw new Error(`Missing '${lang}' name for species id ${species.id}`);
  }
  return entry.name;
}

async function main() {
  const ids = Array.from({ length: MAX_DEX_ID }, (_, i) => i + 1);
  const batchSize = 10;
  const entries: PokedexEntry[] = [];

  for (let i = 0; i < ids.length; i += batchSize) {
    const batch = ids.slice(i, i + batchSize);
    const results = await Promise.all(batch.map(fetchSpecies));
    for (const species of results) {
      entries.push({
        id: species.id,
        nameEn: extractName(species, 'en'),
        nameDe: extractName(species, 'de'),
        generation: generationForId(species.id),
      });
    }
    process.stdout.write(`\rFetched ${Math.min(i + batchSize, ids.length)}/${ids.length}`);
    if (i + batchSize < ids.length) {
      await new Promise((r) => setTimeout(r, 150));
    }
  }
  process.stdout.write('\n');

  entries.sort((a, b) => a.id - b.id);

  if (entries.length !== MAX_DEX_ID) {
    throw new Error(`Expected ${MAX_DEX_ID} entries, got ${entries.length}`);
  }
  for (let i = 0; i < entries.length; i++) {
    if (entries[i].id !== i + 1) {
      throw new Error(`Gap or duplicate detected at index ${i}: id=${entries[i].id}, expected ${i + 1}`);
    }
  }

  const lines = entries.map(
    (e) =>
      `  { id: ${e.id}, nameEn: ${JSON.stringify(e.nameEn)}, nameDe: ${JSON.stringify(e.nameDe)}, generation: ${e.generation} },`
  );

  const output = `// AUTO-GENERATED by scripts/generate-pokedex-data.ts — do not edit by hand.
// Run \`npm run gen:data\` to regenerate.

export interface PokedexEntry {
  id: number;
  nameEn: string;
  nameDe: string;
  generation: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
}

export const POKEDEX: PokedexEntry[] = [
${lines.join('\n')}
];
`;

  mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
  writeFileSync(OUTPUT_FILE, output);
  console.log(`Wrote ${entries.length} entries to ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
